//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Encryption.Breaking.Bll.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Encryption.Breaking.Bll.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;a&quot;:8.17,&quot;b&quot;:1.49,&quot;c&quot;:2.78,&quot;d&quot;:4.25,&quot;e&quot;:12.7,&quot;f&quot;:2.23,&quot;g&quot;:2.02,&quot;h&quot;:6.09,&quot;i&quot;:6.97,&quot;j&quot;:0.15,&quot;k&quot;:0.77,&quot;l&quot;:4.03,&quot;m&quot;:2.41,&quot;n&quot;:6.75,&quot;o&quot;:7.51,&quot;p&quot;:1.93,&quot;q&quot;:0.1,&quot;r&quot;:5.99,&quot;s&quot;:6.33,&quot;t&quot;:9.06,&quot;u&quot;:2.76,&quot;v&quot;:0.98,&quot;w&quot;:2.36,&quot;x&quot;:0.15,&quot;y&quot;:1.97,&quot;z&quot;:0.07}.
        /// </summary>
        internal static string frequencies {
            get {
                return ResourceManager.GetString("frequencies", resourceCulture);
            }
        }
    }
}
